### PR TITLE
GUI - Fix Antenna Elevation indicator 3rd party compatibility

### LINKED ISSUE #1021: Loading ACRE breaks ACE's blood volume icon
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98 Profiling` 
- **CBA:** `3.15.1 stable`
- **ACE3** `3.13.4 stable`
- **ACRE2:** `2.7.4.1027 stable`

**Description:**
Loading ACRE seems to break the new ACE3 medical feedback icon that shows when the player has a low blood level. It's supposed to show up in the upper left corner of the stance indicator after a certain threshold of blood loss, but something in ACRE breaks it.

**Steps to reproduce:**
- Go to into any mission with the icon enabled
- Wound yourself to start bleeding
- Wait until the medical status change into "Lost a lot of blood"

**Expected behavior:**
After the "Lost a loot of blood" threshold, a blood droplet icon should appear in the stance indicator and dynamically adapt to your blood level and bleeding status.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- RPT: [gist](https://gist.github.com/aradiel/664f7b818a76a0b3d183230796588ad6)
- ACRE log: [gist](https://gist.github.com/aradiel/9d07db682703bfdfa5f6a6d6df2279c8)

**Additional context:**
I theorized that perhaps the presence antenna direction indicator was the culprit, but even with no radios it still didn't show up

### PR DESCRIPTION
**Pull request by jonpas**
**When merged this pull request will:**
- Fix #1021 
- Simplify Antenna Elevation UI config
  - Use defines
  - Remove controls group (unnecessary)

### CODE REVIEW

File: addons/sys_gui/RscInGameUI.hpp [hunk 1]
```diff
@@ -1,59 +1,17 @@
...
-                    text= QPATHTOF(data\ui\stand_straight.paa);
-                    colorBackground[] = {
-                        "profileNamespace getVariable ['IGUI_BCG_RGB_R', 0]",
-                        "profileNamespace getVariable ['IGUI_BCG_RGB_G', 1]",
-                        "profileNamespace getVariable ['IGUI_BCG_RGB_B', 1]",
-                        "profileNamespace getVariable ['IGUI_BCG_RGB_A', 0.8]"
-                    };
-                };
+            text = QPATHTOF(data\ui\stand_straight.paa);
+            colorBackground[] = {
```
Comment (mharis001) [inline addons/sys_gui/RscInGameUI.hpp]: Can replace with `IGUI_BCG_COLOR` from `\a3\ui_f\hpp\defineCommonColors.inc`.

**Review by Soldia1138 — COMMENTED** [review]
Looking good. I like @mharis001 comment. Will approve after changes are implemented

**Review by Soldia1138 — APPROVED** [review]
